/**
 * Single source of truth for every content type the platform supports.
 * The dashboard grid, sidebar quick-links, and (in Phase 4) the generator
 * routing all read from this list — add a new content type here once.
 */
import {
  Instagram,
  Facebook,
  Linkedin,
  Twitter,
  MessageCircle,
  MapPin,
  Package,
  Search,
  Newspaper,
  Mail,
  MessageSquareText,
  Youtube,
  Film,
  Megaphone,
  PartyPopper,
  Star,
  Tag,
  Lightbulb,
  MousePointerClick,
  ImageIcon,
  Video,
} from 'lucide-react';

export const CONTENT_TYPES = [
  {
    slug: 'instagram',
    label: 'Instagram Post',
    description: 'Captions, hashtags & emoji-rich posts',
    icon: Instagram,
    category: 'Social Media',
  },
  {
    slug: 'facebook',
    label: 'Facebook Post',
    description: 'Engagement-focused updates',
    icon: Facebook,
    category: 'Social Media',
  },
  {
    slug: 'linkedin',
    label: 'LinkedIn Post',
    description: 'Professional, thought-leadership tone',
    icon: Linkedin,
    category: 'Social Media',
  },
  {
    slug: 'twitter',
    label: 'X (Twitter) Post',
    description: 'Punchy, character-limited copy',
    icon: Twitter,
    category: 'Social Media',
  },
  {
    slug: 'whatsapp',
    label: 'WhatsApp Promotion',
    description: 'Broadcast-ready promo messages',
    icon: MessageCircle,
    category: 'Social Media',
  },
  {
    slug: 'google-business',
    label: 'Google Business Description',
    description: 'Local listing descriptions',
    icon: MapPin,
    category: 'SEO',
  },
  {
    slug: 'product-description',
    label: 'Product Description',
    description: 'Conversion-focused product copy',
    icon: Package,
    category: 'Content Writing',
  },
  {
    slug: 'seo-meta-title',
    label: 'SEO Meta Title',
    description: 'Search-optimized page titles',
    icon: Search,
    category: 'SEO',
  },
  {
    slug: 'seo-meta-description',
    label: 'SEO Meta Description',
    description: 'Click-worthy search snippets',
    icon: Search,
    category: 'SEO',
  },
  {
    slug: 'seo-keywords',
    label: 'SEO Keywords',
    description: 'Ranked keyword suggestions',
    icon: Search,
    category: 'SEO',
  },
  {
    slug: 'blog-article',
    label: 'Blog Article',
    description: 'Full long-form articles',
    icon: Newspaper,
    category: 'Content Writing',
  },
  {
    slug: 'email-campaign',
    label: 'Email Campaign',
    description: 'Subject lines + full email body',
    icon: Mail,
    category: 'Email & SMS',
  },
  {
    slug: 'promotional-sms',
    label: 'Promotional SMS',
    description: 'Short, high-conversion texts',
    icon: MessageSquareText,
    category: 'Email & SMS',
  },
  {
    slug: 'youtube-title',
    label: 'YouTube Title',
    description: 'Clickable, search-friendly titles',
    icon: Youtube,
    category: 'Video & Audio',
  },
  {
    slug: 'youtube-description',
    label: 'YouTube Description',
    description: 'SEO-rich video descriptions',
    icon: Youtube,
    category: 'Video & Audio',
  },
  {
    slug: 'shorts-script',
    label: 'Shorts/Reels Script',
    description: 'Short-form video scripts',
    icon: Film,
    category: 'Video & Audio',
  },
  {
    slug: 'ad-copy',
    label: 'Ad Copy',
    description: 'Paid campaign headlines & body',
    icon: Megaphone,
    category: 'Content Writing',
  },
  {
    slug: 'festival-greeting',
    label: 'Festival Greeting',
    description: 'Culturally-tuned festive posts',
    icon: PartyPopper,
    category: 'Branding',
  },
  {
    slug: 'review-reply',
    label: 'Customer Review Reply',
    description: 'On-brand responses to reviews',
    icon: Star,
    category: 'Branding',
  },
  {
    slug: 'business-tagline',
    label: 'Business Tagline',
    description: 'Short, memorable brand lines',
    icon: Tag,
    category: 'Branding',
  },
  {
    slug: 'marketing-ideas',
    label: 'Marketing Ideas',
    description: 'Campaign & content brainstorms',
    icon: Lightbulb,
    category: 'Branding',
  },
  {
    slug: 'cta-suggestions',
    label: 'CTA Suggestions',
    description: 'Call-to-action variations',
    icon: MousePointerClick,
    category: 'Branding',
  },
  {
    slug: 'image-prompt',
    label: 'Image Prompt',
    description: 'AI image-generation prompts',
    icon: ImageIcon,
    category: 'Video & Audio',
  },
  {
    slug: 'video-prompt',
    label: 'Video Prompt',
    description: 'AI video-generation prompts',
    icon: Video,
    category: 'Video & Audio',
  },
];

export const CATEGORY_ORDER = [
  'Social Media',
  'SEO',
  'Content Writing',
  'Email & SMS',
  'Video & Audio',
  'Branding',
];
